#@TYPE: Machine
#@NAME: S4SK machine
#@DESCRIPTION: Machine configuration for running ironhide

SOC_FAMILY = "r8a779f4"
SOC_FAMILY =. "rcar-gen4:"

require conf/machine/rcars4.inc

# Device tree
KERNEL_DEVICETREE = "\
    renesas/r8a779f4-s4sk.dtb \
"
SERIAL_CONSOLES = "921600;ttySC0"
# u-boot configure
UBOOT_MACHINE = "r8a779f4_s4sk_defconfig"

